/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jmdb_tutorial_jni_CHelloWorld */

#ifndef _Included_jmdb_tutorial_jni_CHelloWorld
#define _Included_jmdb_tutorial_jni_CHelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jmdb_tutorial_jni_CHelloWorld
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jmdb_tutorial_jni_CHelloWorld_sayHello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
